/* eslint-disable */
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EmailAddressVerifiedEvent {
  id: string;
  eventType: "EMAIL_ADDRESS_VERIFIED";
  createdAt: string;
  data: VerifiedEmailAddress;
}
export interface VerifiedEmailAddress {
  emailAddress?: string;
  verifiedAt?: string;
}
export interface NewsletterSubscription {
  id: string;
  firstName: string;
  emailAddress: string;
  newsletterId: string;
  verifiedEmailAddress?: string;
  informedConsent: string;
  subscribedAt: string;
  unsubscribedAt?: string;
  updatedAt?: string;
}
