openapi: 3.0.2
info:
  title: Newsletter Subscription API
  version: 1.0.0
  description: An API to manage Newsletter Subscriptions
paths:
  /newsletter-subscriptions:
    summary: Path used to manage the list of newslettersubscriptions.
    description: >-
      The REST endpoint/path used to list and create zero or more `NewsletterSubscription` entities. 
      This path contains a `GET` and `POST` operation to perform the list and create tasks,
      respectively.
    post:
      x-amazon-apigateway-integration:
        responses:
          default:
            statusCode: "201"
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy
        uri: ${createNewsletterSubscriptionUri}
      requestBody:
        description: A new `NewsletterSubscription` to be created.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewsletterSubscription"
        required: true
      responses:
        "201":
          description: Successful response.
      operationId: createNewsletterSubscription
      summary: Create a NewsletterSubscription
      description: Creates a new instance of a `NewsletterSubscription`.
components:
  schemas:
    NewsletterSubscription:
      title: NewsletterSubscription
      description: ""
      required:
        - emailAddress
        - id
        - informedConsent
        - subscribedAt
        - newsletterId
        - firstName
      type: object
      properties:
        id:
          pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
          type: string
          example: 757f2ef1-08dd-4856-a375-22daf5beb19b
        firstName:
          minLength: 2
          type: string
          example: Aisha
        emailAddress:
          type: string
          example: a.jones@abc.com
        newsletterId:
          pattern: '^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$'
          type: string
          example: 66e4c6f6-3263-4fba-99a9-ff188c50befc
        verifiedEmailAddress:
          pattern: '[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+'
          type: string
          example: a.jones@abc.com
        informedConsent:
          pattern: '[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+'
          type: string
          example: I agree to receive emails from DevMastery.com
        subscribedAt:
          format: date-time
          type: string
          example: "2023-02-02T00:00:00Z"
      example:
        id: 757f2ef1-08dd-4856-a375-22daf5beb19b
        firstName: Aisha
        emailAddress: a.jones@abc.com
        newsletterId: 66e4c6f6-3263-4fba-99a9-ff188c50befc
        verifiedEmailAddress: a.jones@abc.com
        informedConsent: I agree to receive emails from DevMastery.com
        subscribedAt: "2023-02-02T00:00:00Z"
